### ISSUE TITLE
Meteor installation does not work

### ISSUE THREAD

**Issue by DavidSichau** [aedm/minimeteor#10]
I tried to use your docker container to build my app. However the installation of meteor seems to not work.

Do you know what the Problem can be?
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Reset branch 'develop'
Your branch is up-to-date with 'origin/develop'.
KernelVersion: 4.4.0-59-generic
Os: linux
BuildTime: 2017-01-10T23:09:49.630531934+00:00
ApiVersion: 1.24
Version: 1.12.6-cs6
GitCommit: 712e864
Arch: amd64
GoVersion: go1.6.4
Starting build of index.docker.io/davidsichau/react_et:develop...
Step 1 : FROM aedm/minimeteor
# Executing 8 build triggers...
Step 1 : ADD . /app
Step 1 : WORKDIR /app
---> Running in d340b254ff56
Step 1 : ENV DEBIAN_FRONTEND noninteractive
---> Running in d861262a7331
Step 1 : RUN /minimeteor/onbuild.sh
---> Running in 39ca192396aa
[minimeteor] Installing build tools
debconf: delaying package configuration, since apt-utils is not installed
update-alternatives: warning: skip creation of /usr/share/man/man1/w.1.gz because associated file /usr/share/man/man1/w.procps.1.gz (of link group w) doesn't exist
invoke-rc.d: policy-rc.d denied execution of start.
update-alternatives: warning: skip creation of /usr/share/man/man1/view.1.gz because associated file /usr/share/man/man1/see.1.gz (of link group view) doesn't exist
[minimeteor] Installing Meteor
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 7786 0 7786 0 0 132k 0 --:--:-- --:--:-- --:--:-- 380k
Downloading Meteor distribution
tar:
.meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm/node_modules/regjsparser/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm/node_modules/regjsparser/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm/node_modules/regjsparser: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.6.13.0.1vga3ib++os+web.browser+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
[minimeteor] Installing NPM dependencies
[minimeteor] Building Meteor app
sudo: meteor: command not found
sudo: meteor: command not found
```

**Comment by b-long** [comment]
There's a large community behind this project: https://hub.docker.com/r/mquandalle/wekan/ . Recommend checking out their Docker image.

**Comment by aedm** [comment]
Do you use Windows? I got similar error messages when I tried building Meteor/Docker images on Windows.

**Comment by DavidSichau** [comment]
It is a linux build server in the docker cloud:

```
KernelVersion: 4.4.0-59-generic
Os: linux
BuildTime: 2017-01-10T23:09:49.630531934+00:00
ApiVersion: 1.24
Version: 1.12.6-cs6
GitCommit: 712e864
Arch: amd64
GoVersion: go1.6.4
```

**Comment by 0o-de-lally** [comment]
@DavidSichau have you tried the same build on Quay.io? I've had numerous problems with the Docker Cloud build and all meteor + docker images.

**Comment by 0o-de-lally** [comment]
@aedm Congratulations on this package I think it's the best I've seen. It built seamlessly on Quay.io on the first try. Thanks!

**Comment by aedm** [comment]
This doesn't seem like a MiniMeteor issue, it's a standard Meteor installation inside a container that fails.

When I had this error last time I had to modify the storage driver to "aufs". Can you change that on Docker Cloud?

**Comment by aedm** [comment]
Okay, I see now that Docker Cloud uses a different build infrastructure than Docker Hub, and it really doesn't work, I got the same error message. I'm afraid I can't really do much about it. 

But as a workaround, you could try using Docker Hub automatic builds instead. Docker Cloud seems to work with Docker Hub repositories, too.

**Comment by 0o-de-lally** [comment]
Hi guys just to be clear, I am having success BUILDING the image using docker cloud (and docker hub). 
See the log from a fresh automated build on docker cloud (link)
[successful docker cloud minimeteor build.txt](https://github.com/aedm/minimeteor/files/805445/successful.docker.cloud.minimeteor.build.txt)

**Comment by 0o-de-lally** [comment]
Just updating this with my tests. Quay.io, Docker Hub and Docker Cloud all conclude building with a 'success'  result. But when deploying on Docker Cloud I get: Error: can't cd to /home/user/meteor-app/bundle/programs/server/ 

Also noted here: https://github.com/aedm/minimeteor/issues/11

**Comment by aedm** [comment]
I just tried Docker Cloud again, and now I was able to build and run the images succesfully. Maybe it's just a one-off, but installing Meteor was succesful, and I didn't get the `tar` error. Please retry your builds and make sure they aren't cached.

**Comment by kizbitz** [comment]
Been testing builds with this project over the last week - Leaving a couple notes for anyone else running into this error...

- Docker Hub and Cloud now use the same build code in our backend (They used to be different build systems)
- If you're getting the `Directory renamed before its status could be extracted` error when you're using the the Docker Cloud UI to set up your build, bump up the build instance size and see if you still get the error. In my tests I'd get this error every time using the small instance size. It's too small and running out of resources.

**Comment by aedm** [comment]
@DavidSichau does switching to larger build nodes fix your problem?

**Comment by aedm** [comment]
Since the Docker Cloud issue seems to be resolved, I'm closing this issue.
