### ISSUE TITLE
Settings.json?

### ISSUE THREAD

**Issue by ethanwillis** [aedm/minimeteor#16]
How do we define what settings.json to use with our meteor application? For example I'm using a Dockerfile, but there's no way to pass in an argument for a setting.json file.

**Comment by ethanwillis** [comment]
It looks like I just actually set it as an environment variable https://github.com/meteorhacks/meteord/issues/35

**Comment by aedm** [comment]
It's documented here: http://docs.meteor.com/api/core.html#Meteor-settings
