### ISSUE TITLE
mounts denied issue with TMPDIR

### ISSUE THREAD

**Issue by philcruz** [aedm/minimeteor#20]
Apparently, OSX sets $TMPDIR environment variable like /var/folders/qj/nqf7nmns3kz2kwsdsldw8h7h0000gn/T/. Using the latest Docker '/var' is not one of the default shared folders. I added '/var' but still got an error 

```Karambit.local ➜  tyton-app git:(docker) ✗ .scripts/build.sh tyton
Using temp dir: /var/folders/qj/nqf7nmns3kz2kwsdsldw8h7h0000gn/T/tmp.W8DcrYNB
[minimeteor] Copying project files to temp directory
cp: ./.meteor/local/dev_bundle/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp: No such file or directory
[minimeteor] Writing Meteor build script
[minimeteor] Setting executable rights on build script
[minimeteor] Starting Meteor container
docker: Error response from daemon: Mounts denied: sxfs/#namespaces for more info.
.
f7nmns3kz2kwsdsldw8h7h0000gn/T/tmp.W8DcrYNB
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
```

Seems like this issue https://forums.docker.com/t/getting-mounts-denied-on-previously-working-container-after-upgrading-to-v1-12-0-beta18-3-gec40b14/17546

I changed the build.sh script to explicitly set the TEMPDIR like

```
TEMPDIR=`mktemp -d /tmp/minimeteor/XXXXX`
```

since /tmp is by default shared. Might make sense to change the build.sh.

**Comment by aedm** [comment]
@philcruz Thanks for sharing. So if I understand correctly, directories returned by `mktemp` can't be mounted on OSX by default?

**Comment by philcruz** [comment]
To clarify, here are the docs for mktemp https://www.mktemp.org/manual.html. If there is no $TMPDIR it will make a temp dir in /tmp which is fine. 

The issue is that OSX sets a $TMPDIR rooted in /var https://apple.stackexchange.com/questions/94964/where-is-the-temp-folder 

'/var' is not by default a folder that can be mounted by Docker. But even if you add '/var' to the shared folders it apparently can't be mounted for some reason.

**Comment by vuhrmeister** [comment]
For me even directories below `/tmp` are not mounted. Whereas this works (though not intended):

```
TEMPDIR=`mktemp -d ~/.tmp.minimeteor.XXXXXX` 
```

**Comment by aedm** [comment]
It has been fixed. Thanks for the report, sorry for the long delay. Please reopen if it still doesn't work.
