### ISSUE TITLE
Support of private npm modules 

### ISSUE THREAD

**Issue by sokki** [aedm/minimeteor#6]
Would be nice to have a build argument `NPM_TOKEN` to use private npm modules.

also see: https://docs.npmjs.com/private-modules/docker-and-private-modules

**Comment by aedm** [comment]
Hey, sorry for taking so long. I don't have much time these days, but I'll definitely take a look in the next 2-3 weeks.

**Comment by aedm** [comment]
Solved by https://github.com/aedm/minimeteor/pull/7
